Basic Setup Complete
Theres more to be done with this repo, but for now Im ready to stop playing with this - what we have is good enough.
Future work would be to integrate better into an install script and go from there.

diff --git a/install_environment b/install_environment
--- a/install_environment
+++ b/install_environment
@@ -1,13 +1,34 @@
 #!/usr/bin/env zsh
 
-echo "[INFO] - Install Brew"
-/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+INSTALL_DIR="$(dirname ${0:A})"
 
-(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/thughes/.zprofile
-eval "$(/opt/homebrew/bin/brew shellenv)"
+
+if ! command -v brew &> /dev/null; then
+    echo "[Error] Must Install Brew." >&2
+    exit 1
+fi
+echo "[INFO] - Root Install Dir [$INSTALL_DIR]"
 
 echo "[INFO] - Install Brew Tooling"
-visit_brewery
+visit_brewery "$INSTALL_DIR"
 
+echo "[INFO] - Config Mac Settings"
 .macos 
+
+echo "[INFO] - Config Dock" 
 .dock
+
+echo "[INFO] - Install and Configure Oh My Zsh"
+# ZSH should be installed, but we'll re-install it just in case. 
+brew install zsh 
+sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
+
+cp "$INSTALL_DIR/resources/mackie.zsh-theme" ~/.oh-my-zsh/themes/
+open "$INSTALL_DIR/resources/dotfile.itermcolors"
+
+# Set ZSH RC
+rm ~/.zshrc
+ln -s "$INSTALL_DIR/.zshrc" ~/.zshrc
+
+# Make Bin Files Executable 
+chmod -R +x "$INSTALL_DIR/bin"
